Traceback (most recent call last):
  File "snippet.py", line 39, in <module>
    main()
  File "snippet.py", line 8, in main
    f = open(sys.argv[1])
IndexError: list index out of range
