Traceback (most recent call last):
  File "snippet.py", line 23, in <module>
    with rasterio.drivers():
TypeError: 'module' object is not callable
