Traceback (most recent call last):
  File "snippet.py", line 13, in <module>
    from fuse import FUSE, FuseOSError, Operations, LoggingMixIn
  File "/usr/local/lib/python2.7/site-packages/fuse.py", line 115, in <module>
    raise EnvironmentError('Unable to find libfuse')
EnvironmentError: Unable to find libfuse
